---

- name: Fail if required Prometheus settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - prometheus_identifier
    - prometheus_uid
    - prometheus_gid
    - prometheus_container_network
